@startuml
!pragma layout smetana
set namespaceSeparator none
usecase "(8) trump" as id0x0
usecase "(5) inmigrantes" as id0x1
usecase "(5) minneapolis" as id0x2
usecase "(4) pensiones" as id0x3
usecase "(4) regularizacion" as id0x4
usecase "(3) decreto" as id0x5
usecase "(3) deal" as id0x6
usecase "(3) pretti" as id0x7
usecase "(3) avec" as id0x8
usecase "(3) minnesota" as id0x9
usecase "(2) junts" as id0x10
usecase "(2) revalorizacion" as id0x11
@enduml